# Generated by Selenium IDE
# El usuario crea una cuenta con el nombre John Doe, verifica si la pagina guarda la informacion

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSegundo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_segundo(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("messismo@example.com")
    self.driver.find_element(By.ID, "password").send_keys("messismo")
    self.driver.find_element(By.ID, "cpassword").send_keys("messismo")
    self.driver.find_element(By.NAME, "firstName").send_keys("John")
    self.driver.find_element(By.NAME, "lastName").send_keys("Doe")
    self.driver.find_element(By.NAME, "address1").click()
    self.driver.find_element(By.NAME, "address1").send_keys("1600 Pennsylvania Avenue NW, Washington")
    self.driver.find_element(By.NAME, "address2").click()
    self.driver.find_element(By.NAME, "address2").send_keys("1651 Pennsylvania Avenue NW, Washington")
    self.driver.find_element(By.NAME, "zipcode").click()
    self.driver.find_element(By.NAME, "zipcode").send_keys("37188")
    self.driver.find_element(By.NAME, "city").click()
    self.driver.find_element(By.NAME, "city").send_keys("Washington D.C")
    self.driver.find_element(By.NAME, "state").click()
    self.driver.find_element(By.NAME, "state").send_keys("Washington D.C")
    self.driver.find_element(By.NAME, "country").click()
    self.driver.find_element(By.NAME, "country").send_keys("United States")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("1111-1111")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("messismo@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("messismo")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) > input").click()
    user_name = self.driver.find_element(By.CLASS_NAME, "dropbtn").text
    assert "John" in user_name
  
